server:
  port: 8875

spring:
  application:
    name: rediscache
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sccp2?autoReconnect=true&useSSL=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1


mybatis:
  mapper-locations: classpath:mapper/*.xml


logging:
  level:
    com:
      sunwoda:
        demo:
          dao: debug
